Picture/config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :images
    resources :friends
    resources :users

    root to: "images#index"
  end

  get 'friends/index'

  get 'friends/create'

  get 'friends/destroy'

  resources :images
  resources :users
  resources :friends
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'sessions' => 'sessions#create', as: :create

  get 'sessions/destroy'

  root 'pages#home'

  get 'login' => 'sessions#new'

  get 'logout' => 'sessions#destroy'
  get 'about' => 'pages#about', as: :about
  get 'contact' => 'pages#contact', as: :contact
  get 'register' => 'users#new', as: :register
  get 'info' => 'persionals#personal_page'
  get 'auth/:provider/callback', to: "sessions#create"
  get 'newimage' => 'images#new'
  get 'share' => 'images#share'
  get 'unshare' => 'images#unshare'
  resources :sessions, only: [:new, :create, :destroy]
end

Picture/app/controllers/persionals_controller.rb
class PersionalsController < ApplicationController
	before_action :authorize
	def personal_page
		@user = User.find_by(id: session[:current_user_id])
		@images = Image.where(user_id: session[:current_user_id]).paginate(:page => params[:page], :per_page => 8)
	end
end

Picture/app/views/persionals/_list_image.html.erb
<div class="row">
	<% @images.each do |image|%>
	<div class="col-sm-3 col-lg-3 col-md-3">
		<div class="thumbnail">
		<%= image_tag "/image/#{image.id}/cover/#{image.cover_filename}",:id => "img_#{image.id}" , :class => "img-thumbnail", :style => "width:100%; height: 200px" %>
			<div class="caption">
				<h4><textarea rows="1" disabled="disabled"><%=image.script%></textarea></h4>
				<h5><%@user = User.find_by_id(image.user_id)%><%=@user.username%></h5>
				<h5 class="text-muted"><%=image.created_at%></h5>
			</div>
			<% if image.user_id == session[:current_user_id]%>
			<div>
				<%= link_to 'Delete', image, method: :delete, data: { confirm: 'Do you want destroy?' }, class: 'btn btn-danger', style: 'padding: 2px 10px;'%>
				<%= link_to 'Edit', edit_image_path(image), class: 'btn btn-default', style: 'padding: 2px 10px;'%>
            <% if image.status != 1%>
              <%= link_to 'Share',share_path(:id => image.id), class: 'btn btn-info', style: 'padding: 2px 10px;'%>
            <% else %>
              <%= link_to 'Unshare', unshare_path(:id => image.id), class: 'btn btn-danger', style: 'padding: 2px 10px;' %>
            <% end %>
			</div>
			<% end %>
		</div>
	</div>
	<%end%>
</div>
<center><%= will_paginate @images %></center>

Picture/app/views/persionals/personal_page.html.erb
<div class="row">
    <!-- catalog bên trái -->
    <div class="col-xs-3">
        <%= render partial:"users/show"%>
    </div>
    <div class="col-xs-9">
    <%= link_to 'Post image', new_image_path, :class => 'btn btn-primary', :style => "margin-bottom: 16px;" %>
    	<%= render 'list_image'%>
    </div>
</div>