Picture/config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :images
    resources :friends
    resources :users

    root to: "images#index"
  end

  get 'friends/index'

  get 'friends/create'

  get 'friends/destroy'

  resources :images
  resources :users
  resources :friends
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'sessions' => 'sessions#create', as: :create

  get 'sessions/destroy'

  root 'pages#home'

  get 'login' => 'sessions#new'

  get 'logout' => 'sessions#destroy'
  get 'about' => 'pages#about', as: :about
  get 'contact' => 'pages#contact', as: :contact
  get 'register' => 'users#new', as: :register
  get 'info' => 'persionals#personal_page'
  get 'auth/:provider/callback', to: "sessions#create"
  get 'newimage' => 'images#new'
  get 'share' => 'images#share'
  get 'unshare' => 'images#unshare'
  resources :sessions, only: [:new, :create, :destroy]
end

Picture/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | Book Store</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }
    </style>
  <script src="https://npmcdn.com/tether@1.2.4/dist/js/tether.min.js"></script>
  <link href="/css/bootstrap.min.css" rel="stylesheet">
  <link href="/css/font-awesome.min.css" rel="stylesheet">
  <link href="/css/prettyPhoto.css" rel="stylesheet">
  <link href="/css/price-range.css" rel="stylesheet">
  <link href="/css/animate.css" rel="stylesheet">
  <link href="/css/main.css" rel="stylesheet">
  <link href="/css/responsive.css" rel="stylesheet">

  <!--<link rel="shortcut icon" href="images/ico/favicon.ico">-->
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/images/ico/apple-touch-icon-144-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/images/ico/apple-touch-icon-114-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/images/ico/apple-touch-icon-72-precomposed.png">
  <link rel="apple-touch-icon-precomposed" href="/images/ico/apple-touch-icon-57-precomposed.png">
  <!-- Custom CSS -->
  <link href="/css/shop-homepage.css" rel="stylesheet">

  <!-- file css bo sung -->
  <link rel="stylesheet" type="text/css" href="/css/style.css">
  </head>

  <body style="padding-top: 0px;">
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" >My picture</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'Home', root_path, class: "nav-item nav-link " %></li>
        <li><%= link_to 'About', about_path, class: "nav-item nav-link #{yield(:about_active)}" %></li>
        <li><%= link_to 'Contact', contact_path, class: "nav-item nav-link #{yield(:contact_active)}" %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if(session[:current_user_id] == nil)%>
      <li><%= link_to 'Register',register_path, class: "btn btn-outline-success pull-xs-right", style: "margin-left:10px"%></li>
      <li><%= link_to 'login', login_path, class: "btn btn-outline-success pull-xs-right", style: "margin-left:10px"%></li>  
      <% else %>
      <li>
        <% @User = User.find_by(id: session[:current_user_id]) %>
        <%= link_to  info_path do %>
        <%=@User.username%>
        <% end %>
      </li>
      <li><%= link_to 'logout',logout_path, class: "btn btn-outline-success pull-xs-right", style: "margin-left:10px"%></li>
      <%= form_tag(users_path, method: :get) do %>
          <%= text_field_tag :search,nil, placeholder: 'Search friend...', style: "padding-bottom: 7px; padding-top: 3px; padding-left: 4px;"%>
          <%= submit_tag 'Search', :class => 'btn btn-outline-success'%>
      <% end %>
      <%end%>
      </ul>
    </div>
  </div>
</nav>
  <br>
  <br>
  <div class="container" <%=controller_name%> <%=action_name%>>
    <%= yield %>
  </div>
</body>
</html>