Picture/config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :images
    resources :friends
    resources :users

    root to: "images#index"
  end

  get 'friends/index'

  get 'friends/create'

  get 'friends/destroy'

  resources :images
  resources :users
  resources :friends
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'sessions' => 'sessions#create', as: :create

  get 'sessions/destroy'

  root 'pages#home'

  get 'login' => 'sessions#new'

  get 'logout' => 'sessions#destroy'
  get 'about' => 'pages#about', as: :about
  get 'contact' => 'pages#contact', as: :contact
  get 'register' => 'users#new', as: :register
  get 'info' => 'persionals#personal_page'
  get 'auth/:provider/callback', to: "sessions#create"
  get 'newimage' => 'images#new'
  get 'share' => 'images#share'
  get 'unshare' => 'images#unshare'
  resources :sessions, only: [:new, :create, :destroy]
end

Picture/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  attr_accessor :avatar
  has_many :friends
  has_many :friends_users, :through => :friends
  after_save :save_avatar_image, if: :avatar
  def save_avatar_image
    if avatar.original_filename
        filename = avatar.original_filename
  	else
        require 'open-uri'
        open('image.png', 'wb') do |file|
          file << open(avatar_filename).read
        end
    end

  	folder = "public/users/#{id}/avatar"

  	FileUtils::mkdir_p folder
  	f = File.open File.join(folder, filename), "wb"
  	f.write avatar.read()
  	f.close

  	self.avatar = nil
  	update avatar_filename: filename
  end

  def self.sign_in_from_omniauth(auth)
    find_by(provider: auth['provider'], uid: auth['uid']) || create_user_from_omniauth(auth)
  end

  def self.create_user_from_omniauth(auth)
    create(
      uid: auth['uid'],
      provider: auth['provider'],
      avatar_filename: auth['info']['image'],
      name: auth['info']['name'],
      email: auth['info']['email'],
      username: auth['extra']['raw_info']['screen_name'],
      name: auth['extra']['raw_info']['name']
    )
  end
end

Picture/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    if params[:search].present?
      @users = User.where("username like? or name like?", "%#{params[:search]}%", "%#{params[:search]}%")
    else
      @users = User.all
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to info_path, notice: 'User was successfully created.' }
        format.json { render info_path, status: :created, location: @user }
        session[:current_user_id] = @user.id
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :name, :avatar, :gender, :email)
    end
end

Picture/app/helpers/users_helper.rb
module UsersHelper
end

Picture/app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-lg-6">

      <h5>Username</h5>
      <%= f.text_field :username, :class => 'form-group', :style => 'width: 70%; height:40px' %>

      <h5>Password</h5>
      <%= f.password_field :password, :class => 'form-group', :style => 'width: 70%; height:40px'%>

      <h5>Your name</h5>
      <%= f.text_field :name, :class => 'form-group', :style => 'width: 70%; height:40px' %>


      <h5></h5>
    </div>
    <div class="col-lg-6">

      <h5>Gender</h5>
      <%= f.select(:gender, options_for_select([['female', 2], ['male', 1]]), {}, {class: "form-control", :style => 'width: 70%; height:40px'}) %>

      <h5>Email</h5>
      <%= f.text_field :email, :class => 'form-group', :style => 'width: 70%; height:40px'%>

      <h5>Avatar</h5>
      <%= f.file_field :avatar, :class => 'form-group', :style => 'width: 70%; height:40px'%>

    </div>
  </div>
    
  <div class="actions">
      <%= f.submit 'Submit' , :class => 'btn btn-success' %>
  </div>
<% end %>

Picture/app/views/users/_show.html.erb
  <div>
    <%= image_tag "/users/#{@user.id}/avatar/#{@user.avatar_filename}", :size => "260x180" if @user.avatar_filename? %>
  </div>
    <div class="alert alert-info" >
      <strong>Username:</strong>
      <%= @user.username %>
    </div>
    <div class="alert alert-info" >
      <strong>Name:</strong>
      <%= @user.name %>
    </div>
    <div class="alert alert-info" >
      <strong>Gender:</strong>
      <%= @user.gender = 1? "male": "female" %>
    </div>
    <div class="alert alert-info">
      <strong>Email:</strong>
      <%= @user.email %>
    </div>
<br>
<div class="text-xs-right">
  <%= link_to 'Edit', edit_user_path(@user), :class => 'btn btn-success' %>
  <%= link_to 'Friend', friends_path, :class => 'btn btn-info' %>
</div>

Picture/app/views/users/_user.html.erb
<div class="row card" style="margin-left: 150px; margin-right: 150px;">
  <div class="container" style="margin-bottom: -10px; padding-top: 25px;">
      <div class="col-sm-1">
        <div class="text-xs-center"><img src="<%= user.avatar%>" class="img-circle" width="50" height="50"></div>
      </div>
      <div class="col-sm-11">
        <div ><%= user.username %></div>
        <div ><%= user.name %></div>
        <p class="pull-xs-right" style="margin-right: 5px; margin-bottom: 5px;">
          <%= link_to 'Info', user, class: 'btn btn-info', style: 'padding: 2px 10px;' %>
          <% @temp = User.find(session[:current_user_id])%>
          <% if session[:current_user_id] != user.id%>
            <% if @temp.friends.find_by_friend_id(user.id)== nil%>

              <%= link_to "Add Friend", friends_path(:friend_id => user), :method => :post, class: 'btn btn-success', style: 'padding: 2px 10px;'%>
            <% else %>
              <%= link_to 'Unfriend', {controller: "friends", action: "destroy", id: user.id}, method: "delete", class: 'btn btn-danger', style: 'padding: 2px 10px;' %>
            <% end %>
          <% end %>
        </p>
      </div> 
  </div>
</div>

Picture/app/views/users/edit.html.erb
<div class="row">
	<div class="col-lg-2"></div>
	<div class="col-lg-8">
		<%= render 'form', user: @user %>
	</div>
</div>

Picture/app/views/users/index.html.erb
<%= render @users %>

Picture/app/views/users/new.html.erb
<div class="container" style="padding-left: 300px; padding-top: 100px;">
	<%= render 'form', user: @user %>
</div>

Picture/app/views/users/show.html.erb
<div class="container">
<div class="row">
	<div class="col-lg-4">
    <%= image_tag "/users/#{@user.id}/avatar/#{@user.avatar_filename}", :size => "260x180" if @user.avatar_filename? %>
	</div>
	<div class="col-lg-8">
		<div class="alert alert-info" style="width:50%">
			<strong>Username:</strong>
			<%= @user.username %>
		</div>
		<div class="alert alert-info" style="width:50%">
			<strong>Name:</strong>
			<%= @user.name %>
		</div>
	    <div class="alert alert-info" style="width:50%">
	      <strong>Gender:</strong>
	      <%= @user.gender = 1? "male": "female" %>
	    </div>
	    <div class="alert alert-info" style="width:50%">
	      <strong>Email:</strong>
	      <%= @user.email %>
	    </div>
	</div>
</div>
<br>
<div class="text-xs-right">
	<a href="/" class="btn btn-info">Back</a>
	<% if (@user.id == session[:current_user_id]) %>
	<%= link_to 'Edit', edit_user_path(@user), :class => 'btn btn-success' %>
	<% end %>
	<%= link_to 'Friend', friends_path, :class => 'btn btn-success' %>
</div>
</div>